# Generated by Django 3.1.2 on 2020-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTickers',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
