# Generated by Django 3.1.2 on 2020-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTickers2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StockTickers',
        ),
    ]
