# Generated by Django 3.1.2 on 2020-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0002_auto_20201009_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='StockTickers2',
        ),
    ]
